apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-app
  template:
    metadata:
      labels:
        app: file-app
    spec:
      containers:
        - name: file-app-container
          image: rahulguglani/file-app:latest
          ports:
            - containerPort: 3000
