name: Build and Push Docker Image

on:     # this github action will work when we push some changes in main branch
  push:
    branches:
      - main  

jobs:   # this contains different jobs to be done when this action is triggerd
  build-and-push:   # job1: build and push docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code         
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build -t rahulguglani/file-app:latest . --push
  
  run-container:      # job2: running container using bash script
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Run Docker container
        run: |
          docker buildx create --use
          docker run -d -p 3000:3000 rahulguglani/file-app:latest

# for automating kubernetes deployment
# name: Deploy to Kubernetes

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
      
#     - name: Set up Kubernetes CLI
#       uses: azure/setup-kubectl@v1
      
#     - name: Apply Kubernetes manifests
#       run: |
#         kubectl apply -f kubernetes/deployment.yaml
#         kubectl apply -f kubernetes/service.yaml
          